name: 'docker-state cache'
description: 'Cache /var/lib/docker state to improve workflow execution time'
author: '@win-t'
runs:
  using: 'node12'
  main: 'dist/index.js'
  post: 'dist/index.js'
  post-if: 'success()'
